baseURL = "https://s204151.github.io/CSS_webpage/"
title = "CSS Final Project Group 21"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Khalil Ahmadi(s204161)", "Michael Damholt(s204151)", "Mathias Dyhr(s204156)"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com/drive/folders/1RdU0mMRiBL9uTIWgPd8ZTfrs3qKUc8qB"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

